ecommerce/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),        
    path('',include('store.urls')),
    
    
     
]

store/urls.py
from django.contrib.auth import views as auth_views # type: ignore
from django.urls import path  # type: ignore
from . import views
app_name = 'store'

urlpatterns = [
    path('',views.home,name='home'),
    path('index/',views.index,name='index'),
    path('home/', views.home,name='home'),
    path('about/',views.about,name='about'),
    path('new/',views.new,name='new'),
    path('populer/',views.populer,name='populer'),
    path('register/',views.register,name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/',views.logout_view, name='logout'),
    path('cart/',views.cart_view, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('items/',views.items, name='items'),
    path('cart/remove/<int:product_id>/',views.remove_from_cart, name='remove_from_cart'),
    path('cart/clear/', views.clear_cart, name='clear_cart'),
    path('cart/increase/<int:product_id>/', views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:product_id>/', views.decrease_quantity, name='decrease_quantity'),
    path("payment/", views.payment_request, name="payment"),
    path('shipping_address/',views.shipping_address_view,name='shipping_address'),
    path('create-order/', views.create_order, name='create_order'),
    path('create-order/', views.create_order, name='create_order'),
    path('success/',views.success,name='success'),
    path('create-order/<int:shipping_id>/', views.create_order, name='create_order'),
    path('order-summary/<int:order_id>/', views.order_summary, name='order_summary'),
    path('order-history/',views.order_history, name='order_history')
    # path('order_summary/<int:order_id>/',views.order_summary,name='order_summary'),
    # path('payment/callback/', views.payment_callback, name='payment_callback')

    
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>{% block title %}Marketim{% endblock %}</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'store/assets/favicon.ico' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Kendi CSS -->
    <link href="{% static 'store/css/styles.css' %}" rel="stylesheet">

    {% block extra_head %}{% endblock %}
</head>

<body class="d-flex flex-column min-vh-100">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            {% if user.is_authenticated %}
                    <span class="navbar-text me-3">
                        Merhaba, {{ user.username }}
                    </span>

                    {% endif %}
            <a class="navbar-brand" href="{% url 'store:home' %}">Mağazam</a>                       
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'store:home' %}">Ana Sayfa</a></li>                    
                    <li class="nav-item"><a class="nav-link" href="{% url 'store:about' %}">Hakkımızda</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'store:order_history' %}">Sipariş Geçmişim</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">Mağaza</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'store:items' %}">Tüm Ürünler</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="{% url 'store:populer' %}">Popüler Ürünler</a></li>
                            <li><a class="dropdown-item" href="{% url 'store:new' %}">Yeni Ürünler</a></li>
                            

                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <a href="{% url 'store:cart' %}" class="btn btn-outline-dark">
                    <i class="bi-cart-fill me-1"></i>
                    Sepetim
                    <span class="badge bg-dark text-white ms-1 rounded-pill">
                        {{request.session.cart|length|default:"0"}}
                    </span>
                    </a>

            {% if user.is_authenticated %}

    <li class="nav-item">
        <a href="{% url 'store:logout' %}" class="btn btn-danger btn-sm ms-2">Çıkış Yap</a>
    </li>
    
{% else %}
    <li class="nav-item">
        <a href="{% url 'store:login' %}" class="btn btn-secondary btn-sm ms-2">Giriş Yap</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'store:register' %}" class="btn btn-primary btn-sm ms-2">Kayıt Ol</a>
    </li>
    
    
{% endif %}

                               
                </form>
            </div>
        </div>
    </nav>
{% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">{% block header_title %}Mağaza{% endblock %}</h1>
                <p class="lead fw-normal text-white-50 mb-0">{% block header_subtitle %}Mağazamıza hoş geldiniz!{% endblock %}</p>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <main class="flex-fill">
        <div class="container my-4">
            {% block content %}{% endblock %}
        </div>
    </main>

    <!-- Footer-->
    <footer class="py-5 bg-dark mt-auto">
        <div class="container">
            <p class="m-0 text-center text-white">&copy; My Website</p>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'store/js/scripts.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>